apiVersion: v1
kind: Service
metadata:
  name: prometheus-nodeport
  namespace: prometheus
  labels:
    app: prometheus-nodeport
spec:
  selector:
    app: prometheus-grafana
  type: NodePort
  ports:
  - nodePort: 32000
    port: 80
    targetPort: 80
    protocol: TCP

