apiVersion: apps/v1
kind: Deployment
metadata:
  name: 603ba47b83a938d4abae59dd
  namespace: mc-servers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 603ba47b83a938d4abae59dd
  template:
    metadata:
      labels:
        app: 603ba47b83a938d4abae59dd
    spec:
      nodeSelector:
        gameServer: "True"
      tolerations:
      - key: "gameServer"
        value: "True"
        effect: "NoExecute"
      volumes:
        - name: minecraft-pv-storage
          persistentVolumeClaim:
             claimName: testpvc
      containers:
      - image: itzg/minecraft-server:latest
        name: minecraft-server
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "3Gi"
            cpu: "1500m"
        env:
        - name: MEMORY
          value: "2G"

        #- name: ENABLE_AUTOPAUSE
          # value: "TRUE"
        
        #- name: AUTOPAUSE_TIMEOUT_EST
          #value: "60"

        - name: TYPE
          value: "PAPER"

        - name: EULA
          value: "TRUE"

        - name: MAX_PLAYERS
          value: "5"

        - name: VERSION
          value: "LATEST"

        - name: SERVER_NAME
          value: "testServer"

        - name: DIFFICULTY 
          value: "NORMAL"

        - name:  WHITELIST
          value: null

        - name: OPS
          value: null

        - name: OVERRIDE_SERVER_PROPERTIES
          value: "true"

        ports:
        - containerPort: 25565
          name: minecraft
          protocol: TCP
        volumeMounts:
          - mountPath: "/data"
            name: minecraft-pv-storage
