apiVersion: apps/v1
kind: Deployment
metadata:
  name: 603ba47b83a938d4abae59dd
  namespace: mc-servers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 603ba47b83a938d4abae59dd
  template:
    metadata:
      labels:
        app: 603ba47b83a938d4abae59dd
    spec:
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.0.0.10
        searches:
          -  default.svc.cluster.local
          -  svc.cluster.local
          -  cluster.local
        options:
          -  name: ndots
             value: "5"
      volumes:
        - name: minecraft-pv-storage
          persistentVolumeClaim:
             claimName: testpvc
      containers:
      - image: itzg/minecraft-server
        name: minecraft-server
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        env:
        - name: MEMORY
          value: "2g"

        #- name: ENABLE_AUTOPAUSE
          # value: "TRUE"
        
        #- name: AUTOPAUSE_TIMEOUT_EST
          #value: "60"

        - name: TYPE
          value: "VANILLA"

        - name: EULA
          value: "TRUE"

        - name: MAX_PLAYERS
          value: "5"

        - name: VERSION
          value: "LATEST"

        - name: SERVER_NAME
          value: "testServer"

        - name: DIFFICULTY 
          value: "NORMAL"

        - name:  WHITELIST
          value: null

        - name: OPS
          value: null

        - name: OVERRIDE_SERVER_PROPERTIES
          value: "true"

        ports:
        - containerPort: 25565
          name: minecraft
          protocol: TCP
        volumeMounts:
          - mountPath: "/data"
            name: minecraft-pv-storage
