apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 607aa9e5f18679607bb4acf8
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: minecraftsc
