apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-pvc-001
  annotations:
    volume.beta.kubernetes.io/storage-class: "minecraftsc"
spec:
  accessModes:
   - ReadWriteMany
  resources:
    requests:
      storage: 7Gi
