apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
  namespace: web
  labels:
    app: front-end
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
      - name: front-end
        image: ilmal/08ng5749f92j58f74f283705fj2034f587204-frontend:latest
        ports:
        - containerPort: 31000
      nodeSelector:
        type: "web"

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: web
  labels:
    app: frontend
spec:
  selector:
    app: front-end
  type: NodePort
  ports:
  - nodePort: 31000
    port: 31000
    targetPort: 31000
    protocol: TCP

