apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: web
  name: mccontroller-deployment
  labels:
    app: mccontroller
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: mccontroller
  template:
    metadata:
      labels:
        app: mccontroller
    spec:
      containers:
      - name: mccontroller
        image: ilmal/09n754y60959360m53v8754ymn9305n76_mc-k8s-controller:latest
        ports:
        - containerPort: 4000

---

apiVersion: v1
kind: Service
metadata:
  name: mc-controller-service
  namespace: web
spec:
  type: NodePort
  selector:
    app: mccontroller
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 4000
      targetPort: 4000
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 31005

