apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: web
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ilmal/08ng5749f92j58f74f283705fj2034f587204-frontend:latest
        ports:
        - containerPort: 3000

