apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: null
spec:
  nodeSelector:
    gameServer: "True"
  tolerations:
  - key: "gameServer"
    value: "True"
    effect: "NoExecute"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: minecraftsc