# apiVersion: v1
# kind: Service
# metadata:
#   name: custom_service_name
#   labels:
#     app: custom_deployment_name
# spec:
#   nodeSelector:
#     gameServer: "True"
#   tolerations:
#   - key: "gameServer"
#     value: "True"
#     effect: "NoExecute"
#   selector:
#     app: custom_deployment_name
#   type: NodePort
#   ports:
#   - nodePort: 
#     port: 25565
#     targetPort: 25565
#     protocol: TCP

apiVersion: v1
kind: Service
metadata:
  namespace: mc-servers
  name: custom_service_name
  annotations: 
    mc-router.itzg.me/externalServerName: "test.mc.servers.u1.se"
spec:
  ports:
  - port: 25565
  selector:
    app: custom_deployment_name
