# This is a basic workflow to help you get started with Actions

name: update docker images

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ production ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      
      - name: execute py script # run the run.py to get the latest data
        run: |
          cd ./client && python edit_package.json.py
      
      - name: docker login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: client build
        run: |
          docker build ./client -t ilmal/08ng5749f92j58f74f283705fj2034f587204-frontend:latest
      - name: server build
        run: | 
          docker build ./server -t ilmal/947ng59234ngh56943n5g2n4735g29345g7n24395gn-backend:latest
      - name: customAPI build
        run: | 
          docker build ./k8s_custom_API -t ilmal/09n754y60959360m53v8754ymn9305n76_mc-k8s-controller:latest
      - name: docker push
        run: | 
          docker push ilmal/08ng5749f92j58f74f283705fj2034f587204-frontend:latest
          docker push ilmal/947ng59234ngh56943n5g2n4735g29345g7n24395gn-backend:latest
          docker push ilmal/09n754y60959360m53v8754ymn9305n76_mc-k8s-controller:latest

